### ISSUE TITLE
[Bug]: Player construction only facing default direction

### ISSUE THREAD

**Issue by Superbigyam** [igorkis-scrts/A3-Antistasi-Plus#69] opened 2021-10-17 07:16 UTC
### Describe the bug

Since 1.8 version updated, player buildings like sandbags can rotate during planning stage, but only facing default direction after placement.

### How to reproduce

In version 1.8, player construction planning can rotate, but build it will reset its facing to default direction.

### Version

1.8

### Have you altered the code?

No

### What i have changed

```markdown
NO change
```

### Map

Altis

### What server?

Private dedicated server

### Time bug occured (Server time/UTC)

OCT 16, after updated to 1.8

### Mods

```html
CBA_A3
ARMA III Chinese Localization Enhanced
DUI - Squad Radar
Enhanced Movement
RHSAFRF
RHSGREF
RHSSAF
RHSUSAF
NIArms All in One
```

**Comment by igorkis-scrts** [comment] 2021-10-17 07:33
Closed as duplicate of #68.

**Closed by igorkis-scrts** 2021-10-17 07:33 UTC
Labels: bug
