### ISSUE TITLE
[Bug]: Tanoa not available

### ISSUE THREAD

**Issue by Para0234** [igorkis-scrts/A3-Antistasi-Plus#86] opened 2023-01-05 16:41 UTC
### Describe the bug

Up until the 2.0 update, Tanoa and some other maps were all available to play. These maps are available on the Antistasi Community 3.0.0 build and on version 1.8.3.2 . As the removal of maps isn't indicated in the 2.0 patchnote, is the removal an abnormality, I decided to open this ticket as a bug.

### How to reproduce

> Load the game with Antistasi Plus charged as a mod
> Host a new session
> Go to "Tanoa" as the map
> Fail to find "Antistasi Plus" in the missions

### Version

2.0

### Have you altered the code?

No

### Map

Tanoa

### What server?

LAN Hosted

**Comment by igorkis-scrts** [comment] 2023-01-05 19:56
It is indicated in changelog, removal and additions sections:
> Total list of supported terrains - Altis, Malden, Sefrou Ramal, New Esseker, Livonia, Chernarus 2020, Napf, Vidda, Virolahti
> Other terrains are not yet supported, many of them will be ported in the next versions of Antistasi Plus
Tanoa support is planned in the future.

I close this ticket as it is not a bug by any measures.

**Closed by igorkis-scrts** 2023-01-05 19:56 UTC
Labels: bug
